version: "3"

volumes:
  mongo:
  redis:

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
#    build: ./nginx/Dockerfile
    volumes:
      - .:/app
    links:
      - app_node1:app_node1
#      - app_node2:app_node2
    ports:
      - 80:80
      - 443:443

  app_node1:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
    build: .
    volumes:
      - .:/app
    ports:
      - 10080:8080
    environment:
      - HOST=app_node1
      - PORT=10080
      - MONGO_DB_URL=mongodb://mongodb:27017/grain_db
      - SESSION_SECRET=shhhhhhh2342g3v
      - REDIS_SESSION_URL=redis
      - REDIS_SESSION_PORT=6379
    links:
      - mongodb
      - redis
    depends_on:
      - mongodb
      - redis

#  app_node2:
#    build: ./app/Dockerfile
#    volumes:
#      - .:/app
#    ports:
#      - 10081:8081
#    environment:
#      - HOST=app_node2
#      - PORT=10081
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user"
      - MONGODB_PASS="pass"
    volumes:
      - mongo:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  mongoclient:
    image: mongoclient/mongoclient:latest
    hostname: mongoclient
    environment:
      - MONGO_URL=mongodb://mongodb:27017/grain_db
    depends_on:
      - mongodb
    volumes:
      - mongo:/data/db
    ports:
      - 3300:3000

  redis:
    image: redis:3.2-alpine
    volumes:
      - redis:/data

