version: "3"

services:
  nginx:
    build: ./docker/nginx
    volumes:
      - .:/app
    depends_on:
      - app
    links:
      - app:app
    ports:
      - 80:80
      - 443:443
#    networks:
#      store:
#        ipv4_address: 192.168.50.10

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 10080:8080
      - 10443:8443
#    networks:
#      store:
#        ipv4_address: 192.168.50.20

#networks:
#  store:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#      - subnet: 192.168.50.0/24

