version: "3"

services:
  nginx:
    build: nginx
    volumes:
      - .:/app
    links:
      - app_node1:app_node1
      - app_node2:app_node2
    ports:
      - 80:80
      - 443:443
#    networks:
#      store:
#        ipv4_address: 192.168.50.10

  app_node1:
    build: ./app/Dockerfile
    volumes:
      - .:/app
    ports:
      - 10080:8080
    environment:
      - HOST=app_node1
      - PORT=10080
  app_node2:
    build: ./app/Dockerfile
    volumes:
      - .:/app
    ports:
      - 10081:8081
    environment:
      - HOST=app_node2
      - PORT=10081
  #    networks:
#      store:
#        ipv4_address: 192.168.50.20

#networks:
#  store:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#      - subnet: 192.168.50.0/24

