export const AUDIT_MODAL_OPEN = 'AUDIT_MODAL_OPEN';
export const AUDIT_MODAL_DATA_LOADED = 'AUDIT_MODAL_DATA_LOADED';
export const AUDIT_MODAL_DATA_LOADING_ERROR = 'AUDIT_MODAL_DATA_LOADING_ERROR';
export const AUDIT_MODAL_CANCEL = 'AUDIT_MODAL_CANCEL';
