/**
 * User: Vadym Semeniuk
 * Date: 23.07.18
 */

export const ACCEPTING_OFFER_ORDER_RESERVE_REQUEST = 'ACCEPTING_OFFER_ORDER_RESERVE_REQUEST';
export const ACCEPTING_OFFER_ORDER_RESERVE_SUCCESS = 'ACCEPTING_OFFER_ORDER_RESERVE_SUCCESS';
export const ACCEPTING_OFFER_ORDER_RESERVE_FAIL = 'ACCEPTING_OFFER_ORDER_RESERVE_FAIL';

export const DECLINE_REJECT_OFFER_REQUEST = 'DECLINE_REJECT_OFFER_REQUEST';
export const DECLINE_REJECT_OFFER_SUCCESS = 'DECLINE_REJECT_OFFER_SUCCESS';
export const DECLINE_REJECT_OFFER_FAIL = 'DECLINE_REJECT_OFFER_FAIL';
