/**
 * User: Vadym Semeniuk
 * Date: 16.07.18
 */
export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

export const CHANGE_ORDER_REQUEST = 'CHANGE_ORDER_REQUEST';
export const CHANGE_ORDER_SUCCESS = 'CHANGE_ORDER_SUCCESS';
export const CHANGE_ORDER_FAIL = 'CHANGE_ORDER_FAIL';

export const CHANGE_ORDER_STATUS_REQUEST = 'CHANGE_ORDER_STATUS_REQUEST';
export const CHANGE_ORDER_STATUS_SUCCESS = 'CHANGE_ORDER_STATUS_SUCCESS';
export const CHANGE_ORDER_STATUS_FAIL = 'CHANGE_ORDER_STATUS_FAIL';

